"use client";

import Link from "next/link";
import "./globals.css";
import styles from "./layout.module.css";
import { usePathname } from "next/navigation";
import BackButton from "@ui/BackButton/BackButton";
import { Suspense } from "react";
import Loading from "./loading";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <div className={styles.page}>
          <nav className={styles.sidebar}>
            {pathname !== "/" && <BackButton className={styles.backButton} />}
            <ul>
              <li>
                <Link
                  className={`${
                    pathname === "/" ? styles.sidebarSelected : ""
                  } ${styles.sidebarItem}`}
                  href="/"
                >
                  Home
                </Link>
              </li>
              <li>
                <Link
                  className={`${
                    pathname.includes('/vehicles') ? styles.sidebarSelected : ""
                  } ${styles.sidebarItem}`}
                  href="/vehicles"
                >
                  Vehicles
                </Link>
              </li>
              <li>
                <Link
                  className={`${
                    pathname.includes("/people") ? styles.sidebarSelected : ""
                  } ${styles.sidebarItem}`}
                  href="/people"
                >
                  People
                </Link>
              </li>
            </ul>
          </nav>
          <Suspense fallback={<Loading />}>
            <main>{children}</main>
          </Suspense>
        </div>
      </body>
    </html>
  );
}
