import Navigation from "ui/Navigation";
import "./globals.css";
import styles from "./layout.module.css";

const links = [
  {
      title: 'Home',
      url: '/'
  },
  {
      title: 'Vehicles',
      url: '/vehicles'
  },
  {
      title: 'People',
      url: '/people'
  },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <header>
          <div className={styles.header}>NextJS Tutorial App</div>
          <nav className={styles.navigation}>
            <Navigation links={links} />
          </nav>
        </header>
        <main className={styles.main}>{children}</main>
        <footer className={styles.footer}>Created with ❤ at Salucro</footer>
      </body>
    </html>
  );
}
